from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Sequence

import numpy as np


@dataclass(frozen=True)
class ShapeInstance:
    """A closed, consistently indexed statistical apple surface in millimetres."""

    vertices_mm: np.ndarray
    faces: np.ndarray
    coefficients_sigma: np.ndarray

    def inset_vertices_mm(self, thickness_mm: float) -> np.ndarray:
        """Return a radial inner surface for a simple constant-thickness skin model."""
        if thickness_mm < 0.0:
            raise ValueError("thickness_mm must be non-negative")
        radii = np.linalg.norm(self.vertices_mm, axis=1)
        if np.any(radii <= thickness_mm):
            raise ValueError("thickness exceeds the local surface radius")
        return self.vertices_mm * ((radii - thickness_mm) / radii)[:, None]

    def write_ply(self, path: Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="ascii", newline="\n") as stream:
            stream.write("ply\nformat ascii 1.0\n")
            stream.write("comment generated by fruitsim StatisticalFujiShape\n")
            stream.write(f"element vertex {len(self.vertices_mm)}\n")
            stream.write("property double x\nproperty double y\nproperty double z\n")
            stream.write(f"element face {len(self.faces)}\n")
            stream.write("property list uchar int vertex_indices\nend_header\n")
            np.savetxt(stream, self.vertices_mm, fmt="%.10g %.10g %.10g")
            for face in self.faces:
                stream.write(f"3 {int(face[0])} {int(face[1])} {int(face[2])}\n")
        return path


class StatisticalFujiShape:
    """Mean radial apple surface plus PCA deformation modes.

    The class name follows the requested modelling layer. The bundled Zenodo
    record does not itself identify the cultivar, so ``cultivar_status`` in the
    artifact must be inspected before making a Fuji-specific scientific claim.
    """

    def __init__(
        self,
        directions: np.ndarray,
        mean_radius_mm: np.ndarray,
        mode_deformations_mm: np.ndarray,
        faces: np.ndarray,
        metadata: dict[str, Any],
    ) -> None:
        self.directions = np.asarray(directions, dtype=np.float64)
        self.mean_radius_mm = np.asarray(mean_radius_mm, dtype=np.float64)
        self.mode_deformations_mm = np.asarray(mode_deformations_mm, dtype=np.float64)
        self.faces = np.asarray(faces, dtype=np.int64)
        self.metadata = dict(metadata)
        self._validate()

    def _validate(self) -> None:
        if self.directions.ndim != 2 or self.directions.shape[1] != 3:
            raise ValueError("directions must have shape (N, 3)")
        count = self.directions.shape[0]
        if self.mean_radius_mm.shape != (count,):
            raise ValueError("mean_radius_mm must match direction count")
        if self.mode_deformations_mm.ndim != 2 \
                or self.mode_deformations_mm.shape[1] != count:
            raise ValueError("mode_deformations_mm must have shape (K, N)")
        if self.faces.ndim != 2 or self.faces.shape[1] != 3:
            raise ValueError("faces must have shape (M, 3)")
        norms = np.linalg.norm(self.directions, axis=1)
        if not np.allclose(norms, 1.0, atol=1.0e-7):
            raise ValueError("all directions must be unit vectors")
        if np.any(self.mean_radius_mm <= 0.0) or not np.isfinite(
            self.mode_deformations_mm
        ).all():
            raise ValueError("shape radii and modes must be finite and positive at the mean")
        if self.faces.size and (self.faces.min() < 0 or self.faces.max() >= count):
            raise ValueError("face index is outside the vertex array")

    @property
    def mode_count(self) -> int:
        return int(self.mode_deformations_mm.shape[0])

    @classmethod
    def load(cls, path: Path) -> "StatisticalFujiShape":
        document = json.loads(Path(path).read_text(encoding="utf-8"))
        if document.get("schema_version") != 1 \
                or document.get("geometry_type") != "StatisticalFujiShape":
            raise ValueError("unsupported statistical shape artifact")
        modes = document.get("pca_modes", [])
        return cls(
            directions=np.asarray(document["directions"], dtype=np.float64),
            mean_radius_mm=np.asarray(document["mean_radius_mm"], dtype=np.float64),
            mode_deformations_mm=np.asarray(
                [mode["deformation_mm"] for mode in modes], dtype=np.float64
            ).reshape(len(modes), -1),
            faces=np.asarray(document["faces"], dtype=np.int64),
            metadata={key: value for key, value in document.items()
                      if key not in {"directions", "mean_radius_mm", "pca_modes", "faces"}},
        )

    def sample(
        self,
        coefficients_sigma: Sequence[float] | None = None,
        *,
        seed: int | None = None,
        mode_count: int | None = None,
        sigma_clip: float = 3.0,
    ) -> ShapeInstance:
        if sigma_clip <= 0.0:
            raise ValueError("sigma_clip must be positive")
        active = self.mode_count if mode_count is None else int(mode_count)
        if active < 0 or active > self.mode_count:
            raise ValueError("mode_count is outside the available PCA modes")
        if coefficients_sigma is None:
            coefficients = np.random.default_rng(seed).normal(size=active)
        else:
            coefficients = np.asarray(coefficients_sigma, dtype=np.float64)
            if coefficients.shape != (active,):
                raise ValueError("coefficient count must equal active mode_count")
        coefficients = np.clip(coefficients, -sigma_clip, sigma_clip)
        radii = self.mean_radius_mm.copy()
        if active:
            radii += coefficients @ self.mode_deformations_mm[:active]
        if np.any(radii <= 0.0):
            raise ValueError(
                "sampled PCA coefficients produced a non-positive radius; reduce sigma_clip"
            )
        return ShapeInstance(
            vertices_mm=self.directions * radii[:, None],
            faces=self.faces.copy(),
            coefficients_sigma=coefficients,
        )

    def mean_shape(self) -> ShapeInstance:
        return self.sample(np.zeros(self.mode_count), mode_count=self.mode_count)
